-- NBA Accreditation Faculty Information System schema (MySQL 8+)

SET NAMES utf8mb4;
SET FOREIGN_KEY_CHECKS = 0;

CREATE TABLE IF NOT EXISTS users (
  id CHAR(36) NOT NULL DEFAULT (UUID()),
  auth_user_id CHAR(36) NOT NULL,
  email VARCHAR(255) NOT NULL,
  password_hash VARCHAR(255) NULL,
  role ENUM('admin', 'faculty', 'viewer', 'student') NOT NULL DEFAULT 'viewer',
  created_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  PRIMARY KEY (id),
  UNIQUE KEY uq_users_auth_user_id (auth_user_id),
  UNIQUE KEY uq_users_email (email)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS faculty (
  id CHAR(36) NOT NULL DEFAULT (UUID()),
  user_id CHAR(36) NULL,
  name VARCHAR(255) NOT NULL,
  designation VARCHAR(255) NOT NULL,
  department VARCHAR(255) NOT NULL,
  email VARCHAR(255) NOT NULL,
  phone VARCHAR(50) NOT NULL,
  photo_url TEXT NULL,
  cv_url TEXT NULL,
  linkedin_url TEXT NULL,
  github_url TEXT NULL,
  google_scholar_url TEXT NULL,
  website_url TEXT NULL,
  research_area TEXT NULL,
  bio TEXT NULL,
  experience_teaching INT NOT NULL DEFAULT 0,
  experience_industry INT NOT NULL DEFAULT 0,
  is_approved TINYINT(1) NOT NULL DEFAULT 0,
  approved_by CHAR(36) NULL,
  approved_at DATETIME(6) NULL,
  created_by CHAR(36) NULL,
  updated_by CHAR(36) NULL,
  created_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  updated_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6),
  PRIMARY KEY (id),
  KEY idx_faculty_user_id (user_id),
  KEY idx_faculty_approved_by (approved_by),
  KEY idx_faculty_created_by (created_by),
  KEY idx_faculty_updated_by (updated_by),
  CONSTRAINT fk_faculty_user_id FOREIGN KEY (user_id) REFERENCES users(auth_user_id) ON DELETE SET NULL,
  CONSTRAINT fk_faculty_approved_by FOREIGN KEY (approved_by) REFERENCES users(auth_user_id) ON DELETE SET NULL,
  CONSTRAINT fk_faculty_created_by FOREIGN KEY (created_by) REFERENCES users(auth_user_id) ON DELETE SET NULL,
  CONSTRAINT fk_faculty_updated_by FOREIGN KEY (updated_by) REFERENCES users(auth_user_id) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS qualifications (
  id CHAR(36) NOT NULL DEFAULT (UUID()),
  faculty_id CHAR(36) NOT NULL,
  degree VARCHAR(255) NOT NULL,
  specialization VARCHAR(255) NULL,
  institute TEXT NOT NULL,
  year INT NULL,
  is_approved TINYINT(1) NOT NULL DEFAULT 0,
  approved_by CHAR(36) NULL,
  approved_at DATETIME(6) NULL,
  created_by CHAR(36) NULL,
  updated_by CHAR(36) NULL,
  created_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  updated_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6),
  PRIMARY KEY (id),
  KEY idx_qualifications_faculty (faculty_id, is_approved),
  CONSTRAINT fk_qualifications_faculty FOREIGN KEY (faculty_id) REFERENCES faculty(id) ON DELETE CASCADE,
  CONSTRAINT fk_qualifications_approved_by FOREIGN KEY (approved_by) REFERENCES users(auth_user_id) ON DELETE SET NULL,
  CONSTRAINT fk_qualifications_created_by FOREIGN KEY (created_by) REFERENCES users(auth_user_id) ON DELETE SET NULL,
  CONSTRAINT fk_qualifications_updated_by FOREIGN KEY (updated_by) REFERENCES users(auth_user_id) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS publications (
  id CHAR(36) NOT NULL DEFAULT (UUID()),
  faculty_id CHAR(36) NOT NULL,
  title TEXT NOT NULL,
  authors TEXT NULL,
  journal TEXT NULL,
  year INT NULL,
  doi VARCHAR(255) NULL,
  type VARCHAR(100) NULL,
  indexed VARCHAR(255) NULL,
  reference_url TEXT NULL,
  pdf_url TEXT NULL,
  scopus TINYINT(1) NOT NULL DEFAULT 0,
  wos TINYINT(1) NOT NULL DEFAULT 0,
  is_approved TINYINT(1) NOT NULL DEFAULT 0,
  approved_by CHAR(36) NULL,
  approved_at DATETIME(6) NULL,
  created_by CHAR(36) NULL,
  updated_by CHAR(36) NULL,
  created_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  updated_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6),
  PRIMARY KEY (id),
  KEY idx_publications_faculty (faculty_id, is_approved),
  CONSTRAINT fk_publications_faculty FOREIGN KEY (faculty_id) REFERENCES faculty(id) ON DELETE CASCADE,
  CONSTRAINT fk_publications_approved_by FOREIGN KEY (approved_by) REFERENCES users(auth_user_id) ON DELETE SET NULL,
  CONSTRAINT fk_publications_created_by FOREIGN KEY (created_by) REFERENCES users(auth_user_id) ON DELETE SET NULL,
  CONSTRAINT fk_publications_updated_by FOREIGN KEY (updated_by) REFERENCES users(auth_user_id) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS fdp (
  id CHAR(36) NOT NULL DEFAULT (UUID()),
  faculty_id CHAR(36) NOT NULL,
  title TEXT NOT NULL,
  role VARCHAR(255) NULL,
  duration VARCHAR(255) NULL,
  start_date DATE NULL,
  end_date DATE NULL,
  organized_by TEXT NULL,
  is_approved TINYINT(1) NOT NULL DEFAULT 0,
  approved_by CHAR(36) NULL,
  approved_at DATETIME(6) NULL,
  created_by CHAR(36) NULL,
  updated_by CHAR(36) NULL,
  created_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  updated_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6),
  PRIMARY KEY (id),
  KEY idx_fdp_faculty (faculty_id, is_approved),
  CONSTRAINT fk_fdp_faculty FOREIGN KEY (faculty_id) REFERENCES faculty(id) ON DELETE CASCADE,
  CONSTRAINT fk_fdp_approved_by FOREIGN KEY (approved_by) REFERENCES users(auth_user_id) ON DELETE SET NULL,
  CONSTRAINT fk_fdp_created_by FOREIGN KEY (created_by) REFERENCES users(auth_user_id) ON DELETE SET NULL,
  CONSTRAINT fk_fdp_updated_by FOREIGN KEY (updated_by) REFERENCES users(auth_user_id) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS projects (
  id CHAR(36) NOT NULL DEFAULT (UUID()),
  faculty_id CHAR(36) NOT NULL,
  title TEXT NOT NULL,
  funding_agency TEXT NULL,
  amount DECIMAL(12,2) NOT NULL DEFAULT 0,
  year INT NULL,
  status VARCHAR(100) NULL,
  reference_url TEXT NULL,
  pdf_url TEXT NULL,
  is_approved TINYINT(1) NOT NULL DEFAULT 0,
  approved_by CHAR(36) NULL,
  approved_at DATETIME(6) NULL,
  created_by CHAR(36) NULL,
  updated_by CHAR(36) NULL,
  created_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  updated_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6),
  PRIMARY KEY (id),
  KEY idx_projects_faculty (faculty_id, is_approved),
  CONSTRAINT fk_projects_faculty FOREIGN KEY (faculty_id) REFERENCES faculty(id) ON DELETE CASCADE,
  CONSTRAINT fk_projects_approved_by FOREIGN KEY (approved_by) REFERENCES users(auth_user_id) ON DELETE SET NULL,
  CONSTRAINT fk_projects_created_by FOREIGN KEY (created_by) REFERENCES users(auth_user_id) ON DELETE SET NULL,
  CONSTRAINT fk_projects_updated_by FOREIGN KEY (updated_by) REFERENCES users(auth_user_id) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS consultancy (
  id CHAR(36) NOT NULL DEFAULT (UUID()),
  faculty_id CHAR(36) NOT NULL,
  title TEXT NOT NULL,
  company TEXT NULL,
  amount DECIMAL(12,2) NOT NULL DEFAULT 0,
  year INT NULL,
  is_approved TINYINT(1) NOT NULL DEFAULT 0,
  approved_by CHAR(36) NULL,
  approved_at DATETIME(6) NULL,
  created_by CHAR(36) NULL,
  updated_by CHAR(36) NULL,
  created_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  updated_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6),
  PRIMARY KEY (id),
  KEY idx_consultancy_faculty (faculty_id, is_approved),
  CONSTRAINT fk_consultancy_faculty FOREIGN KEY (faculty_id) REFERENCES faculty(id) ON DELETE CASCADE,
  CONSTRAINT fk_consultancy_approved_by FOREIGN KEY (approved_by) REFERENCES users(auth_user_id) ON DELETE SET NULL,
  CONSTRAINT fk_consultancy_created_by FOREIGN KEY (created_by) REFERENCES users(auth_user_id) ON DELETE SET NULL,
  CONSTRAINT fk_consultancy_updated_by FOREIGN KEY (updated_by) REFERENCES users(auth_user_id) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS patents (
  id CHAR(36) NOT NULL DEFAULT (UUID()),
  faculty_id CHAR(36) NOT NULL,
  title TEXT NOT NULL,
  status VARCHAR(100) NULL,
  year INT NULL,
  number VARCHAR(255) NULL,
  reference_url TEXT NULL,
  pdf_url TEXT NULL,
  is_approved TINYINT(1) NOT NULL DEFAULT 0,
  approved_by CHAR(36) NULL,
  approved_at DATETIME(6) NULL,
  created_by CHAR(36) NULL,
  updated_by CHAR(36) NULL,
  created_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  updated_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6),
  PRIMARY KEY (id),
  KEY idx_patents_faculty (faculty_id, is_approved),
  CONSTRAINT fk_patents_faculty FOREIGN KEY (faculty_id) REFERENCES faculty(id) ON DELETE CASCADE,
  CONSTRAINT fk_patents_approved_by FOREIGN KEY (approved_by) REFERENCES users(auth_user_id) ON DELETE SET NULL,
  CONSTRAINT fk_patents_created_by FOREIGN KEY (created_by) REFERENCES users(auth_user_id) ON DELETE SET NULL,
  CONSTRAINT fk_patents_updated_by FOREIGN KEY (updated_by) REFERENCES users(auth_user_id) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS books (
  id CHAR(36) NOT NULL DEFAULT (UUID()),
  faculty_id CHAR(36) NOT NULL,
  title TEXT NOT NULL,
  publisher TEXT NULL,
  isbn VARCHAR(255) NULL,
  year INT NULL,
  reference_url TEXT NULL,
  pdf_url TEXT NULL,
  is_approved TINYINT(1) NOT NULL DEFAULT 0,
  approved_by CHAR(36) NULL,
  approved_at DATETIME(6) NULL,
  created_by CHAR(36) NULL,
  updated_by CHAR(36) NULL,
  created_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  updated_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6),
  PRIMARY KEY (id),
  KEY idx_books_faculty (faculty_id, is_approved),
  CONSTRAINT fk_books_faculty FOREIGN KEY (faculty_id) REFERENCES faculty(id) ON DELETE CASCADE,
  CONSTRAINT fk_books_approved_by FOREIGN KEY (approved_by) REFERENCES users(auth_user_id) ON DELETE SET NULL,
  CONSTRAINT fk_books_created_by FOREIGN KEY (created_by) REFERENCES users(auth_user_id) ON DELETE SET NULL,
  CONSTRAINT fk_books_updated_by FOREIGN KEY (updated_by) REFERENCES users(auth_user_id) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS collaborations (
  id CHAR(36) NOT NULL DEFAULT (UUID()),
  faculty_id CHAR(36) NOT NULL,
  title TEXT NOT NULL,
  organization TEXT NULL,
  country VARCHAR(255) NULL,
  role VARCHAR(255) NULL,
  start_year INT NULL,
  end_year INT NULL,
  is_approved TINYINT(1) NOT NULL DEFAULT 0,
  approved_by CHAR(36) NULL,
  approved_at DATETIME(6) NULL,
  created_by CHAR(36) NULL,
  updated_by CHAR(36) NULL,
  created_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  updated_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6),
  PRIMARY KEY (id),
  KEY idx_collaborations_faculty (faculty_id, is_approved),
  CONSTRAINT fk_collaborations_faculty FOREIGN KEY (faculty_id) REFERENCES faculty(id) ON DELETE CASCADE,
  CONSTRAINT fk_collaborations_approved_by FOREIGN KEY (approved_by) REFERENCES users(auth_user_id) ON DELETE SET NULL,
  CONSTRAINT fk_collaborations_created_by FOREIGN KEY (created_by) REFERENCES users(auth_user_id) ON DELETE SET NULL,
  CONSTRAINT fk_collaborations_updated_by FOREIGN KEY (updated_by) REFERENCES users(auth_user_id) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS miscellaneous_items (
  id CHAR(36) NOT NULL DEFAULT (UUID()),
  faculty_id CHAR(36) NOT NULL,
  title TEXT NOT NULL,
  description TEXT NULL,
  reference_url TEXT NULL,
  pdf_url TEXT NULL,
  custom_fields JSON NOT NULL,
  is_approved TINYINT(1) NOT NULL DEFAULT 0,
  approved_by CHAR(36) NULL,
  approved_at DATETIME(6) NULL,
  created_by CHAR(36) NULL,
  updated_by CHAR(36) NULL,
  created_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  updated_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6),
  PRIMARY KEY (id),
  KEY idx_misc_items_faculty (faculty_id, is_approved),
  CONSTRAINT fk_misc_items_faculty FOREIGN KEY (faculty_id) REFERENCES faculty(id) ON DELETE CASCADE,
  CONSTRAINT fk_misc_items_approved_by FOREIGN KEY (approved_by) REFERENCES users(auth_user_id) ON DELETE SET NULL,
  CONSTRAINT fk_misc_items_created_by FOREIGN KEY (created_by) REFERENCES users(auth_user_id) ON DELETE SET NULL,
  CONSTRAINT fk_misc_items_updated_by FOREIGN KEY (updated_by) REFERENCES users(auth_user_id) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS awards (
  id CHAR(36) NOT NULL DEFAULT (UUID()),
  faculty_id CHAR(36) NOT NULL,
  title TEXT NOT NULL,
  membership TEXT NULL,
  honors TEXT NULL,
  contributions TEXT NULL,
  year INT NULL,
  description TEXT NULL,
  is_approved TINYINT(1) NOT NULL DEFAULT 0,
  approved_by CHAR(36) NULL,
  approved_at DATETIME(6) NULL,
  created_by CHAR(36) NULL,
  updated_by CHAR(36) NULL,
  created_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  updated_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6),
  PRIMARY KEY (id),
  KEY idx_awards_faculty (faculty_id, is_approved),
  CONSTRAINT fk_awards_faculty FOREIGN KEY (faculty_id) REFERENCES faculty(id) ON DELETE CASCADE,
  CONSTRAINT fk_awards_approved_by FOREIGN KEY (approved_by) REFERENCES users(auth_user_id) ON DELETE SET NULL,
  CONSTRAINT fk_awards_created_by FOREIGN KEY (created_by) REFERENCES users(auth_user_id) ON DELETE SET NULL,
  CONSTRAINT fk_awards_updated_by FOREIGN KEY (updated_by) REFERENCES users(auth_user_id) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS moocs (
  id CHAR(36) NOT NULL DEFAULT (UUID()),
  faculty_id CHAR(36) NOT NULL,
  course TEXT NOT NULL,
  platform VARCHAR(255) NULL,
  grade VARCHAR(255) NULL,
  year INT NULL,
  is_approved TINYINT(1) NOT NULL DEFAULT 0,
  approved_by CHAR(36) NULL,
  approved_at DATETIME(6) NULL,
  created_by CHAR(36) NULL,
  updated_by CHAR(36) NULL,
  created_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  updated_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6),
  PRIMARY KEY (id),
  KEY idx_moocs_faculty (faculty_id, is_approved),
  CONSTRAINT fk_moocs_faculty FOREIGN KEY (faculty_id) REFERENCES faculty(id) ON DELETE CASCADE,
  CONSTRAINT fk_moocs_approved_by FOREIGN KEY (approved_by) REFERENCES users(auth_user_id) ON DELETE SET NULL,
  CONSTRAINT fk_moocs_created_by FOREIGN KEY (created_by) REFERENCES users(auth_user_id) ON DELETE SET NULL,
  CONSTRAINT fk_moocs_updated_by FOREIGN KEY (updated_by) REFERENCES users(auth_user_id) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS research_proofs (
  id CHAR(36) NOT NULL DEFAULT (UUID()),
  faculty_id CHAR(36) NOT NULL,
  title TEXT NOT NULL,
  proof_url TEXT NOT NULL,
  description TEXT NULL,
  year INT NULL,
  is_approved TINYINT(1) NOT NULL DEFAULT 0,
  approved_by CHAR(36) NULL,
  approved_at DATETIME(6) NULL,
  created_by CHAR(36) NULL,
  updated_by CHAR(36) NULL,
  created_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  updated_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6),
  PRIMARY KEY (id),
  KEY idx_research_proofs_faculty (faculty_id, is_approved),
  CONSTRAINT fk_research_proofs_faculty FOREIGN KEY (faculty_id) REFERENCES faculty(id) ON DELETE CASCADE,
  CONSTRAINT fk_research_proofs_approved_by FOREIGN KEY (approved_by) REFERENCES users(auth_user_id) ON DELETE SET NULL,
  CONSTRAINT fk_research_proofs_created_by FOREIGN KEY (created_by) REFERENCES users(auth_user_id) ON DELETE SET NULL,
  CONSTRAINT fk_research_proofs_updated_by FOREIGN KEY (updated_by) REFERENCES users(auth_user_id) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS audit_log (
  id BIGINT NOT NULL AUTO_INCREMENT,
  table_name VARCHAR(128) NOT NULL,
  row_id CHAR(36) NULL,
  action ENUM('INSERT', 'UPDATE', 'DELETE') NOT NULL,
  changed_by CHAR(36) NULL,
  old_data JSON NULL,
  new_data JSON NULL,
  created_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  PRIMARY KEY (id),
  KEY idx_audit_lookup (table_name, row_id, created_at),
  KEY idx_audit_created_at (created_at)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS notifications (
  id CHAR(36) NOT NULL DEFAULT (UUID()),
  recipient_user_id CHAR(36) NOT NULL,
  title VARCHAR(255) NOT NULL,
  message TEXT NOT NULL,
  is_read TINYINT(1) NOT NULL DEFAULT 0,
  created_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  updated_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6),
  PRIMARY KEY (id),
  KEY idx_notifications_recipient (recipient_user_id, is_read, created_at),
  CONSTRAINT fk_notifications_recipient FOREIGN KEY (recipient_user_id) REFERENCES users(auth_user_id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS latest_achievements (
  id CHAR(36) NOT NULL DEFAULT (UUID()),
  faculty_id CHAR(36) NULL,
  title VARCHAR(255) NOT NULL,
  summary TEXT NULL,
  media_type ENUM('image', 'pdf', 'youtube', 'link') NOT NULL,
  media_url TEXT NOT NULL,
  thumbnail_url TEXT NULL,
  display_order INT NOT NULL DEFAULT 0,
  is_published TINYINT(1) NOT NULL DEFAULT 1,
  published_from DATETIME(6) NULL,
  published_to DATETIME(6) NULL,
  created_by CHAR(36) NULL,
  updated_by CHAR(36) NULL,
  created_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  updated_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6),
  PRIMARY KEY (id),
  KEY idx_latest_achievements_visibility (is_published, display_order, created_at),
  CONSTRAINT fk_latest_achievements_faculty FOREIGN KEY (faculty_id) REFERENCES faculty(id) ON DELETE SET NULL,
  CONSTRAINT fk_latest_achievements_created_by FOREIGN KEY (created_by) REFERENCES users(auth_user_id) ON DELETE SET NULL,
  CONSTRAINT fk_latest_achievements_updated_by FOREIGN KEY (updated_by) REFERENCES users(auth_user_id) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE INDEX idx_faculty_is_approved ON faculty(is_approved);

SET FOREIGN_KEY_CHECKS = 1;
